# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from edo_core_msgs/JointReset.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class JointReset(genpy.Message):
  _md5sum = "a9a93ce1fc39c419654c782e78ed4d90"
  _type = "edo_core_msgs/JointReset"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 joints_mask
uint32 disengage_steps
float32 disengage_offset
"""
  __slots__ = ['joints_mask','disengage_steps','disengage_offset']
  _slot_types = ['uint64','uint32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       joints_mask,disengage_steps,disengage_offset

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(JointReset, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.joints_mask is None:
        self.joints_mask = 0
      if self.disengage_steps is None:
        self.disengage_steps = 0
      if self.disengage_offset is None:
        self.disengage_offset = 0.
    else:
      self.joints_mask = 0
      self.disengage_steps = 0
      self.disengage_offset = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_QIf().pack(_x.joints_mask, _x.disengage_steps, _x.disengage_offset))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.joints_mask, _x.disengage_steps, _x.disengage_offset,) = _get_struct_QIf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_QIf().pack(_x.joints_mask, _x.disengage_steps, _x.disengage_offset))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.joints_mask, _x.disengage_steps, _x.disengage_offset,) = _get_struct_QIf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_QIf = None
def _get_struct_QIf():
    global _struct_QIf
    if _struct_QIf is None:
        _struct_QIf = struct.Struct("<QIf")
    return _struct_QIf
