# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from edo_core_msgs/Payload.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Payload(genpy.Message):
  _md5sum = "2b506a0a9f14e6eb5c73141f070aa0ab"
  _type = "edo_core_msgs/Payload"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 mass
float32 x
float32 y
float32 z
float32 xx
float32 yy
float32 zz
float32 xy
float32 xz
float32 yz"""
  __slots__ = ['mass','x','y','z','xx','yy','zz','xy','xz','yz']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mass,x,y,z,xx,yy,zz,xy,xz,yz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Payload, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mass is None:
        self.mass = 0.
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.xx is None:
        self.xx = 0.
      if self.yy is None:
        self.yy = 0.
      if self.zz is None:
        self.zz = 0.
      if self.xy is None:
        self.xy = 0.
      if self.xz is None:
        self.xz = 0.
      if self.yz is None:
        self.yz = 0.
    else:
      self.mass = 0.
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.xx = 0.
      self.yy = 0.
      self.zz = 0.
      self.xy = 0.
      self.xz = 0.
      self.yz = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_10f().pack(_x.mass, _x.x, _x.y, _x.z, _x.xx, _x.yy, _x.zz, _x.xy, _x.xz, _x.yz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.mass, _x.x, _x.y, _x.z, _x.xx, _x.yy, _x.zz, _x.xy, _x.xz, _x.yz,) = _get_struct_10f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_10f().pack(_x.mass, _x.x, _x.y, _x.z, _x.xx, _x.yy, _x.zz, _x.xy, _x.xz, _x.yz))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.mass, _x.x, _x.y, _x.z, _x.xx, _x.yy, _x.zz, _x.xy, _x.xz, _x.yz,) = _get_struct_10f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10f = None
def _get_struct_10f():
    global _struct_10f
    if _struct_10f is None:
        _struct_10f = struct.Struct("<10f")
    return _struct_10f
