// Generated by gencpp from file edo_core_msgs/AppState.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_APPSTATE_H
#define EDO_CORE_MSGS_MESSAGE_APPSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct AppState_
{
  typedef AppState_<ContainerAllocator> Type;

  AppState_()
    : position(0.0)
    , velocity(0.0)  {
    }
  AppState_(const ContainerAllocator& _alloc)
    : position(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef float _position_type;
  _position_type position;

   typedef float _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::edo_core_msgs::AppState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::AppState_<ContainerAllocator> const> ConstPtr;

}; // struct AppState_

typedef ::edo_core_msgs::AppState_<std::allocator<void> > AppState;

typedef boost::shared_ptr< ::edo_core_msgs::AppState > AppStatePtr;
typedef boost::shared_ptr< ::edo_core_msgs::AppState const> AppStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::AppState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::AppState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::AppState_<ContainerAllocator1> & lhs, const ::edo_core_msgs::AppState_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::AppState_<ContainerAllocator1> & lhs, const ::edo_core_msgs::AppState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::AppState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::AppState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::AppState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::AppState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::AppState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::AppState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::AppState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cf6c2ef6d4814960f7bd2c448525593";
  }

  static const char* value(const ::edo_core_msgs::AppState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cf6c2ef6d481496ULL;
  static const uint64_t static_value2 = 0x0f7bd2c448525593ULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::AppState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/AppState";
  }

  static const char* value(const ::edo_core_msgs::AppState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::AppState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 position\n"
"float32 velocity\n"
;
  }

  static const char* value(const ::edo_core_msgs::AppState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::AppState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AppState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::AppState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::AppState_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_APPSTATE_H
