// Generated by gencpp from file edo_core_msgs/BrakesCheckAck.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_BRAKESCHECKACK_H
#define EDO_CORE_MSGS_MESSAGE_BRAKESCHECKACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct BrakesCheckAck_
{
  typedef BrakesCheckAck_<ContainerAllocator> Type;

  BrakesCheckAck_()
    : state(0)
    , mask(0)  {
    }
  BrakesCheckAck_(const ContainerAllocator& _alloc)
    : state(0)
    , mask(0)  {
  (void)_alloc;
    }



   typedef int8_t _state_type;
  _state_type state;

   typedef uint8_t _mask_type;
  _mask_type mask;





  typedef boost::shared_ptr< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> const> ConstPtr;

}; // struct BrakesCheckAck_

typedef ::edo_core_msgs::BrakesCheckAck_<std::allocator<void> > BrakesCheckAck;

typedef boost::shared_ptr< ::edo_core_msgs::BrakesCheckAck > BrakesCheckAckPtr;
typedef boost::shared_ptr< ::edo_core_msgs::BrakesCheckAck const> BrakesCheckAckConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator1> & lhs, const ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.mask == rhs.mask;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator1> & lhs, const ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7847bd3cb7cd03de2fdad24bf584ab13";
  }

  static const char* value(const ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7847bd3cb7cd03deULL;
  static const uint64_t static_value2 = 0x2fdad24bf584ab13ULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/BrakesCheckAck";
  }

  static const char* value(const ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 state\n"
"uint8 mask\n"
;
  }

  static const char* value(const ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.mask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BrakesCheckAck_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::BrakesCheckAck_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    s << indent << "mask: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_BRAKESCHECKACK_H
