// Generated by gencpp from file edo_core_msgs/CalibCounter.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_CALIBCOUNTER_H
#define EDO_CORE_MSGS_MESSAGE_CALIBCOUNTER_H

#include <ros/service_traits.h>


#include <edo_core_msgs/CalibCounterRequest.h>
#include <edo_core_msgs/CalibCounterResponse.h>


namespace edo_core_msgs
{

struct CalibCounter
{

typedef CalibCounterRequest Request;
typedef CalibCounterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalibCounter
} // namespace edo_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::edo_core_msgs::CalibCounter > {
  static const char* value()
  {
    return "72ca51e2f1b267eff310adf88ee999e0";
  }

  static const char* value(const ::edo_core_msgs::CalibCounter&) { return value(); }
};

template<>
struct DataType< ::edo_core_msgs::CalibCounter > {
  static const char* value()
  {
    return "edo_core_msgs/CalibCounter";
  }

  static const char* value(const ::edo_core_msgs::CalibCounter&) { return value(); }
};


// service_traits::MD5Sum< ::edo_core_msgs::CalibCounterRequest> should match
// service_traits::MD5Sum< ::edo_core_msgs::CalibCounter >
template<>
struct MD5Sum< ::edo_core_msgs::CalibCounterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::CalibCounter >::value();
  }
  static const char* value(const ::edo_core_msgs::CalibCounterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::CalibCounterRequest> should match
// service_traits::DataType< ::edo_core_msgs::CalibCounter >
template<>
struct DataType< ::edo_core_msgs::CalibCounterRequest>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::CalibCounter >::value();
  }
  static const char* value(const ::edo_core_msgs::CalibCounterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::edo_core_msgs::CalibCounterResponse> should match
// service_traits::MD5Sum< ::edo_core_msgs::CalibCounter >
template<>
struct MD5Sum< ::edo_core_msgs::CalibCounterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::CalibCounter >::value();
  }
  static const char* value(const ::edo_core_msgs::CalibCounterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::CalibCounterResponse> should match
// service_traits::DataType< ::edo_core_msgs::CalibCounter >
template<>
struct DataType< ::edo_core_msgs::CalibCounterResponse>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::CalibCounter >::value();
  }
  static const char* value(const ::edo_core_msgs::CalibCounterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_CALIBCOUNTER_H
