// Generated by gencpp from file edo_core_msgs/CalibCounterResponse.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_CALIBCOUNTERRESPONSE_H
#define EDO_CORE_MSGS_MESSAGE_CALIBCOUNTERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct CalibCounterResponse_
{
  typedef CalibCounterResponse_<ContainerAllocator> Type;

  CalibCounterResponse_()
    : cnt(0)  {
    }
  CalibCounterResponse_(const ContainerAllocator& _alloc)
    : cnt(0)  {
  (void)_alloc;
    }



   typedef uint64_t _cnt_type;
  _cnt_type cnt;





  typedef boost::shared_ptr< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CalibCounterResponse_

typedef ::edo_core_msgs::CalibCounterResponse_<std::allocator<void> > CalibCounterResponse;

typedef boost::shared_ptr< ::edo_core_msgs::CalibCounterResponse > CalibCounterResponsePtr;
typedef boost::shared_ptr< ::edo_core_msgs::CalibCounterResponse const> CalibCounterResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator1> & lhs, const ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator2> & rhs)
{
  return lhs.cnt == rhs.cnt;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator1> & lhs, const ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77be2b98f3037c6a78d5698f5338ee01";
  }

  static const char* value(const ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77be2b98f3037c6aULL;
  static const uint64_t static_value2 = 0x78d5698f5338ee01ULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/CalibCounterResponse";
  }

  static const char* value(const ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 cnt\n"
;
  }

  static const char* value(const ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cnt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalibCounterResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::CalibCounterResponse_<ContainerAllocator>& v)
  {
    s << indent << "cnt: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.cnt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_CALIBCOUNTERRESPONSE_H
