// Generated by gencpp from file edo_core_msgs/CalibCounterRequest.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_CALIBCOUNTERREQUEST_H
#define EDO_CORE_MSGS_MESSAGE_CALIBCOUNTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct CalibCounterRequest_
{
  typedef CalibCounterRequest_<ContainerAllocator> Type;

  CalibCounterRequest_()
    : increment(false)  {
    }
  CalibCounterRequest_(const ContainerAllocator& _alloc)
    : increment(false)  {
  (void)_alloc;
    }



   typedef uint8_t _increment_type;
  _increment_type increment;





  typedef boost::shared_ptr< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CalibCounterRequest_

typedef ::edo_core_msgs::CalibCounterRequest_<std::allocator<void> > CalibCounterRequest;

typedef boost::shared_ptr< ::edo_core_msgs::CalibCounterRequest > CalibCounterRequestPtr;
typedef boost::shared_ptr< ::edo_core_msgs::CalibCounterRequest const> CalibCounterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator1> & lhs, const ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.increment == rhs.increment;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator1> & lhs, const ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ab652b8bce1842c58b203fdf082de12";
  }

  static const char* value(const ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ab652b8bce1842cULL;
  static const uint64_t static_value2 = 0x58b203fdf082de12ULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/CalibCounterRequest";
  }

  static const char* value(const ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool increment\n"
;
  }

  static const char* value(const ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.increment);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalibCounterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::CalibCounterRequest_<ContainerAllocator>& v)
  {
    s << indent << "increment: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.increment);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_CALIBCOUNTERREQUEST_H
