// Generated by gencpp from file edo_core_msgs/CollisionThreshold.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_COLLISIONTHRESHOLD_H
#define EDO_CORE_MSGS_MESSAGE_COLLISIONTHRESHOLD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct CollisionThreshold_
{
  typedef CollisionThreshold_<ContainerAllocator> Type;

  CollisionThreshold_()
    : joints_mask(0)
    , threshold(0.0)  {
    }
  CollisionThreshold_(const ContainerAllocator& _alloc)
    : joints_mask(0)
    , threshold(0.0)  {
  (void)_alloc;
    }



   typedef uint64_t _joints_mask_type;
  _joints_mask_type joints_mask;

   typedef float _threshold_type;
  _threshold_type threshold;





  typedef boost::shared_ptr< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> const> ConstPtr;

}; // struct CollisionThreshold_

typedef ::edo_core_msgs::CollisionThreshold_<std::allocator<void> > CollisionThreshold;

typedef boost::shared_ptr< ::edo_core_msgs::CollisionThreshold > CollisionThresholdPtr;
typedef boost::shared_ptr< ::edo_core_msgs::CollisionThreshold const> CollisionThresholdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::CollisionThreshold_<ContainerAllocator1> & lhs, const ::edo_core_msgs::CollisionThreshold_<ContainerAllocator2> & rhs)
{
  return lhs.joints_mask == rhs.joints_mask &&
    lhs.threshold == rhs.threshold;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::CollisionThreshold_<ContainerAllocator1> & lhs, const ::edo_core_msgs::CollisionThreshold_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> >
{
  static const char* value()
  {
    return "585b6a67aae99a6b6c3bc5dce3ab7d3b";
  }

  static const char* value(const ::edo_core_msgs::CollisionThreshold_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x585b6a67aae99a6bULL;
  static const uint64_t static_value2 = 0x6c3bc5dce3ab7d3bULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/CollisionThreshold";
  }

  static const char* value(const ::edo_core_msgs::CollisionThreshold_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 joints_mask\n"
"float32 threshold\n"
;
  }

  static const char* value(const ::edo_core_msgs::CollisionThreshold_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints_mask);
      stream.next(m.threshold);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CollisionThreshold_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::CollisionThreshold_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::CollisionThreshold_<ContainerAllocator>& v)
  {
    s << indent << "joints_mask: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.joints_mask);
    s << indent << "threshold: ";
    Printer<float>::stream(s, indent + "  ", v.threshold);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_COLLISIONTHRESHOLD_H
