// Generated by gencpp from file edo_core_msgs/ControlSwitchRequest.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_CONTROLSWITCHREQUEST_H
#define EDO_CORE_MSGS_MESSAGE_CONTROLSWITCHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct ControlSwitchRequest_
{
  typedef ControlSwitchRequest_<ContainerAllocator> Type;

  ControlSwitchRequest_()
    : mode(0)  {
    }
  ControlSwitchRequest_(const ContainerAllocator& _alloc)
    : mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ControlSwitchRequest_

typedef ::edo_core_msgs::ControlSwitchRequest_<std::allocator<void> > ControlSwitchRequest;

typedef boost::shared_ptr< ::edo_core_msgs::ControlSwitchRequest > ControlSwitchRequestPtr;
typedef boost::shared_ptr< ::edo_core_msgs::ControlSwitchRequest const> ControlSwitchRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator1> & lhs, const ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator1> & lhs, const ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89b81386720be1cd0ce7a3953fcd1b19";
  }

  static const char* value(const ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89b81386720be1cdULL;
  static const uint64_t static_value2 = 0x0ce7a3953fcd1b19ULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/ControlSwitchRequest";
  }

  static const char* value(const ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode\n"
;
  }

  static const char* value(const ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlSwitchRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::ControlSwitchRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_CONTROLSWITCHREQUEST_H
