// Generated by gencpp from file edo_core_msgs/ControlSwitch.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_CONTROLSWITCH_H
#define EDO_CORE_MSGS_MESSAGE_CONTROLSWITCH_H

#include <ros/service_traits.h>


#include <edo_core_msgs/ControlSwitchRequest.h>
#include <edo_core_msgs/ControlSwitchResponse.h>


namespace edo_core_msgs
{

struct ControlSwitch
{

typedef ControlSwitchRequest Request;
typedef ControlSwitchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControlSwitch
} // namespace edo_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::edo_core_msgs::ControlSwitch > {
  static const char* value()
  {
    return "ccce2c131f10776744f7b69253be5d43";
  }

  static const char* value(const ::edo_core_msgs::ControlSwitch&) { return value(); }
};

template<>
struct DataType< ::edo_core_msgs::ControlSwitch > {
  static const char* value()
  {
    return "edo_core_msgs/ControlSwitch";
  }

  static const char* value(const ::edo_core_msgs::ControlSwitch&) { return value(); }
};


// service_traits::MD5Sum< ::edo_core_msgs::ControlSwitchRequest> should match
// service_traits::MD5Sum< ::edo_core_msgs::ControlSwitch >
template<>
struct MD5Sum< ::edo_core_msgs::ControlSwitchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::ControlSwitch >::value();
  }
  static const char* value(const ::edo_core_msgs::ControlSwitchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::ControlSwitchRequest> should match
// service_traits::DataType< ::edo_core_msgs::ControlSwitch >
template<>
struct DataType< ::edo_core_msgs::ControlSwitchRequest>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::ControlSwitch >::value();
  }
  static const char* value(const ::edo_core_msgs::ControlSwitchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::edo_core_msgs::ControlSwitchResponse> should match
// service_traits::MD5Sum< ::edo_core_msgs::ControlSwitch >
template<>
struct MD5Sum< ::edo_core_msgs::ControlSwitchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::ControlSwitch >::value();
  }
  static const char* value(const ::edo_core_msgs::ControlSwitchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::ControlSwitchResponse> should match
// service_traits::DataType< ::edo_core_msgs::ControlSwitch >
template<>
struct DataType< ::edo_core_msgs::ControlSwitchResponse>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::ControlSwitch >::value();
  }
  static const char* value(const ::edo_core_msgs::ControlSwitchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_CONTROLSWITCH_H
