// Generated by gencpp from file edo_core_msgs/DirectKinematicsRequest.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_DIRECTKINEMATICSREQUEST_H
#define EDO_CORE_MSGS_MESSAGE_DIRECTKINEMATICSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <edo_core_msgs/JointsPositions.h>

namespace edo_core_msgs
{
template <class ContainerAllocator>
struct DirectKinematicsRequest_
{
  typedef DirectKinematicsRequest_<ContainerAllocator> Type;

  DirectKinematicsRequest_()
    : positions()  {
    }
  DirectKinematicsRequest_(const ContainerAllocator& _alloc)
    : positions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::edo_core_msgs::JointsPositions_<ContainerAllocator>  _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DirectKinematicsRequest_

typedef ::edo_core_msgs::DirectKinematicsRequest_<std::allocator<void> > DirectKinematicsRequest;

typedef boost::shared_ptr< ::edo_core_msgs::DirectKinematicsRequest > DirectKinematicsRequestPtr;
typedef boost::shared_ptr< ::edo_core_msgs::DirectKinematicsRequest const> DirectKinematicsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator1> & lhs, const ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.positions == rhs.positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator1> & lhs, const ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "634608e33427b3da9c8fae849b2bc252";
  }

  static const char* value(const ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x634608e33427b3daULL;
  static const uint64_t static_value2 = 0x9c8fae849b2bc252ULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/DirectKinematicsRequest";
  }

  static const char* value(const ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/JointsPositions positions\n"
"\n"
"================================================================================\n"
"MSG: edo_core_msgs/JointsPositions\n"
"uint64 joints_mask\n"
"uint8[] joints_type\n"
"float32[] positions\n"
;
  }

  static const char* value(const ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DirectKinematicsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::DirectKinematicsRequest_<ContainerAllocator>& v)
  {
    s << indent << "positions: ";
    s << std::endl;
    Printer< ::edo_core_msgs::JointsPositions_<ContainerAllocator> >::stream(s, indent + "  ", v.positions);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_DIRECTKINEMATICSREQUEST_H
