// Generated by gencpp from file edo_core_msgs/DirectKinematics.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_DIRECTKINEMATICS_H
#define EDO_CORE_MSGS_MESSAGE_DIRECTKINEMATICS_H

#include <ros/service_traits.h>


#include <edo_core_msgs/DirectKinematicsRequest.h>
#include <edo_core_msgs/DirectKinematicsResponse.h>


namespace edo_core_msgs
{

struct DirectKinematics
{

typedef DirectKinematicsRequest Request;
typedef DirectKinematicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DirectKinematics
} // namespace edo_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::edo_core_msgs::DirectKinematics > {
  static const char* value()
  {
    return "53d8dd74fa95a4c65914ef00d095729c";
  }

  static const char* value(const ::edo_core_msgs::DirectKinematics&) { return value(); }
};

template<>
struct DataType< ::edo_core_msgs::DirectKinematics > {
  static const char* value()
  {
    return "edo_core_msgs/DirectKinematics";
  }

  static const char* value(const ::edo_core_msgs::DirectKinematics&) { return value(); }
};


// service_traits::MD5Sum< ::edo_core_msgs::DirectKinematicsRequest> should match
// service_traits::MD5Sum< ::edo_core_msgs::DirectKinematics >
template<>
struct MD5Sum< ::edo_core_msgs::DirectKinematicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::DirectKinematics >::value();
  }
  static const char* value(const ::edo_core_msgs::DirectKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::DirectKinematicsRequest> should match
// service_traits::DataType< ::edo_core_msgs::DirectKinematics >
template<>
struct DataType< ::edo_core_msgs::DirectKinematicsRequest>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::DirectKinematics >::value();
  }
  static const char* value(const ::edo_core_msgs::DirectKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::edo_core_msgs::DirectKinematicsResponse> should match
// service_traits::MD5Sum< ::edo_core_msgs::DirectKinematics >
template<>
struct MD5Sum< ::edo_core_msgs::DirectKinematicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::DirectKinematics >::value();
  }
  static const char* value(const ::edo_core_msgs::DirectKinematicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::DirectKinematicsResponse> should match
// service_traits::DataType< ::edo_core_msgs::DirectKinematics >
template<>
struct DataType< ::edo_core_msgs::DirectKinematicsResponse>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::DirectKinematics >::value();
  }
  static const char* value(const ::edo_core_msgs::DirectKinematicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_DIRECTKINEMATICS_H
