// Generated by gencpp from file edo_core_msgs/InverseKinematics.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_INVERSEKINEMATICS_H
#define EDO_CORE_MSGS_MESSAGE_INVERSEKINEMATICS_H

#include <ros/service_traits.h>


#include <edo_core_msgs/InverseKinematicsRequest.h>
#include <edo_core_msgs/InverseKinematicsResponse.h>


namespace edo_core_msgs
{

struct InverseKinematics
{

typedef InverseKinematicsRequest Request;
typedef InverseKinematicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InverseKinematics
} // namespace edo_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::edo_core_msgs::InverseKinematics > {
  static const char* value()
  {
    return "1c24acd7035fed719a53e12d3c8c16d1";
  }

  static const char* value(const ::edo_core_msgs::InverseKinematics&) { return value(); }
};

template<>
struct DataType< ::edo_core_msgs::InverseKinematics > {
  static const char* value()
  {
    return "edo_core_msgs/InverseKinematics";
  }

  static const char* value(const ::edo_core_msgs::InverseKinematics&) { return value(); }
};


// service_traits::MD5Sum< ::edo_core_msgs::InverseKinematicsRequest> should match
// service_traits::MD5Sum< ::edo_core_msgs::InverseKinematics >
template<>
struct MD5Sum< ::edo_core_msgs::InverseKinematicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::InverseKinematics >::value();
  }
  static const char* value(const ::edo_core_msgs::InverseKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::InverseKinematicsRequest> should match
// service_traits::DataType< ::edo_core_msgs::InverseKinematics >
template<>
struct DataType< ::edo_core_msgs::InverseKinematicsRequest>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::InverseKinematics >::value();
  }
  static const char* value(const ::edo_core_msgs::InverseKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::edo_core_msgs::InverseKinematicsResponse> should match
// service_traits::MD5Sum< ::edo_core_msgs::InverseKinematics >
template<>
struct MD5Sum< ::edo_core_msgs::InverseKinematicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::InverseKinematics >::value();
  }
  static const char* value(const ::edo_core_msgs::InverseKinematicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::InverseKinematicsResponse> should match
// service_traits::DataType< ::edo_core_msgs::InverseKinematics >
template<>
struct DataType< ::edo_core_msgs::InverseKinematicsResponse>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::InverseKinematics >::value();
  }
  static const char* value(const ::edo_core_msgs::InverseKinematicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_INVERSEKINEMATICS_H
