// Generated by gencpp from file edo_core_msgs/JointCalibration.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_JOINTCALIBRATION_H
#define EDO_CORE_MSGS_MESSAGE_JOINTCALIBRATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct JointCalibration_
{
  typedef JointCalibration_<ContainerAllocator> Type;

  JointCalibration_()
    : joints_mask(0)  {
    }
  JointCalibration_(const ContainerAllocator& _alloc)
    : joints_mask(0)  {
  (void)_alloc;
    }



   typedef uint64_t _joints_mask_type;
  _joints_mask_type joints_mask;





  typedef boost::shared_ptr< ::edo_core_msgs::JointCalibration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::JointCalibration_<ContainerAllocator> const> ConstPtr;

}; // struct JointCalibration_

typedef ::edo_core_msgs::JointCalibration_<std::allocator<void> > JointCalibration;

typedef boost::shared_ptr< ::edo_core_msgs::JointCalibration > JointCalibrationPtr;
typedef boost::shared_ptr< ::edo_core_msgs::JointCalibration const> JointCalibrationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::JointCalibration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::JointCalibration_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::JointCalibration_<ContainerAllocator1> & lhs, const ::edo_core_msgs::JointCalibration_<ContainerAllocator2> & rhs)
{
  return lhs.joints_mask == rhs.joints_mask;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::JointCalibration_<ContainerAllocator1> & lhs, const ::edo_core_msgs::JointCalibration_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::JointCalibration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::JointCalibration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::JointCalibration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::JointCalibration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::JointCalibration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::JointCalibration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::JointCalibration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e3c733216f52667eed4e5d125e26029e";
  }

  static const char* value(const ::edo_core_msgs::JointCalibration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe3c733216f52667eULL;
  static const uint64_t static_value2 = 0xed4e5d125e26029eULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::JointCalibration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/JointCalibration";
  }

  static const char* value(const ::edo_core_msgs::JointCalibration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::JointCalibration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 joints_mask\n"
;
  }

  static const char* value(const ::edo_core_msgs::JointCalibration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::JointCalibration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints_mask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointCalibration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::JointCalibration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::JointCalibration_<ContainerAllocator>& v)
  {
    s << indent << "joints_mask: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.joints_mask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_JOINTCALIBRATION_H
