// Generated by gencpp from file edo_core_msgs/JointInit.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_JOINTINIT_H
#define EDO_CORE_MSGS_MESSAGE_JOINTINIT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct JointInit_
{
  typedef JointInit_<ContainerAllocator> Type;

  JointInit_()
    : mode(0)
    , joints_mask(0)
    , reduction_factor(0.0)  {
    }
  JointInit_(const ContainerAllocator& _alloc)
    : mode(0)
    , joints_mask(0)
    , reduction_factor(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint64_t _joints_mask_type;
  _joints_mask_type joints_mask;

   typedef float _reduction_factor_type;
  _reduction_factor_type reduction_factor;





  typedef boost::shared_ptr< ::edo_core_msgs::JointInit_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::JointInit_<ContainerAllocator> const> ConstPtr;

}; // struct JointInit_

typedef ::edo_core_msgs::JointInit_<std::allocator<void> > JointInit;

typedef boost::shared_ptr< ::edo_core_msgs::JointInit > JointInitPtr;
typedef boost::shared_ptr< ::edo_core_msgs::JointInit const> JointInitConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::JointInit_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::JointInit_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::JointInit_<ContainerAllocator1> & lhs, const ::edo_core_msgs::JointInit_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.joints_mask == rhs.joints_mask &&
    lhs.reduction_factor == rhs.reduction_factor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::JointInit_<ContainerAllocator1> & lhs, const ::edo_core_msgs::JointInit_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::JointInit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::JointInit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::JointInit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::JointInit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::JointInit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::JointInit_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::JointInit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e68c8959b591478083b4be2f20df5d8";
  }

  static const char* value(const ::edo_core_msgs::JointInit_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e68c8959b591478ULL;
  static const uint64_t static_value2 = 0x083b4be2f20df5d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::JointInit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/JointInit";
  }

  static const char* value(const ::edo_core_msgs::JointInit_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::JointInit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 mode\n"
"uint64 joints_mask\n"
"float32 reduction_factor\n"
;
  }

  static const char* value(const ::edo_core_msgs::JointInit_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::JointInit_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.joints_mask);
      stream.next(m.reduction_factor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointInit_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::JointInit_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::JointInit_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "joints_mask: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.joints_mask);
    s << indent << "reduction_factor: ";
    Printer<float>::stream(s, indent + "  ", v.reduction_factor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_JOINTINIT_H
