// Generated by gencpp from file edo_core_msgs/JointsPositions.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_JOINTSPOSITIONS_H
#define EDO_CORE_MSGS_MESSAGE_JOINTSPOSITIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct JointsPositions_
{
  typedef JointsPositions_<ContainerAllocator> Type;

  JointsPositions_()
    : joints_mask(0)
    , joints_type()
    , positions()  {
    }
  JointsPositions_(const ContainerAllocator& _alloc)
    : joints_mask(0)
    , joints_type(_alloc)
    , positions(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _joints_mask_type;
  _joints_mask_type joints_mask;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _joints_type_type;
  _joints_type_type joints_type;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _positions_type;
  _positions_type positions;





  typedef boost::shared_ptr< ::edo_core_msgs::JointsPositions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::JointsPositions_<ContainerAllocator> const> ConstPtr;

}; // struct JointsPositions_

typedef ::edo_core_msgs::JointsPositions_<std::allocator<void> > JointsPositions;

typedef boost::shared_ptr< ::edo_core_msgs::JointsPositions > JointsPositionsPtr;
typedef boost::shared_ptr< ::edo_core_msgs::JointsPositions const> JointsPositionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::JointsPositions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::JointsPositions_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::JointsPositions_<ContainerAllocator1> & lhs, const ::edo_core_msgs::JointsPositions_<ContainerAllocator2> & rhs)
{
  return lhs.joints_mask == rhs.joints_mask &&
    lhs.joints_type == rhs.joints_type &&
    lhs.positions == rhs.positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::JointsPositions_<ContainerAllocator1> & lhs, const ::edo_core_msgs::JointsPositions_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::JointsPositions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::JointsPositions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::JointsPositions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::JointsPositions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::JointsPositions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::JointsPositions_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::JointsPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ea3550f10ff0950a480f8a9ea845012";
  }

  static const char* value(const ::edo_core_msgs::JointsPositions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ea3550f10ff0950ULL;
  static const uint64_t static_value2 = 0xa480f8a9ea845012ULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::JointsPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/JointsPositions";
  }

  static const char* value(const ::edo_core_msgs::JointsPositions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::JointsPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 joints_mask\n"
"uint8[] joints_type\n"
"float32[] positions\n"
;
  }

  static const char* value(const ::edo_core_msgs::JointsPositions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::JointsPositions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints_mask);
      stream.next(m.joints_type);
      stream.next(m.positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointsPositions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::JointsPositions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::JointsPositions_<ContainerAllocator>& v)
  {
    s << indent << "joints_mask: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.joints_mask);
    s << indent << "joints_type[]" << std::endl;
    for (size_t i = 0; i < v.joints_type.size(); ++i)
    {
      s << indent << "  joints_type[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.joints_type[i]);
    }
    s << indent << "positions[]" << std::endl;
    for (size_t i = 0; i < v.positions.size(); ++i)
    {
      s << indent << "  positions[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_JOINTSPOSITIONS_H
