// Generated by gencpp from file edo_core_msgs/LoadConfigurationFileRequest.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_LOADCONFIGURATIONFILEREQUEST_H
#define EDO_CORE_MSGS_MESSAGE_LOADCONFIGURATIONFILEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct LoadConfigurationFileRequest_
{
  typedef LoadConfigurationFileRequest_<ContainerAllocator> Type;

  LoadConfigurationFileRequest_()
    {
    }
  LoadConfigurationFileRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> const> ConstPtr;

}; // struct LoadConfigurationFileRequest_

typedef ::edo_core_msgs::LoadConfigurationFileRequest_<std::allocator<void> > LoadConfigurationFileRequest;

typedef boost::shared_ptr< ::edo_core_msgs::LoadConfigurationFileRequest > LoadConfigurationFileRequestPtr;
typedef boost::shared_ptr< ::edo_core_msgs::LoadConfigurationFileRequest const> LoadConfigurationFileRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/LoadConfigurationFileRequest";
  }

  static const char* value(const ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadConfigurationFileRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::edo_core_msgs::LoadConfigurationFileRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_LOADCONFIGURATIONFILEREQUEST_H
