// Generated by gencpp from file edo_core_msgs/LoadConfigurationFile.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_LOADCONFIGURATIONFILE_H
#define EDO_CORE_MSGS_MESSAGE_LOADCONFIGURATIONFILE_H

#include <ros/service_traits.h>


#include <edo_core_msgs/LoadConfigurationFileRequest.h>
#include <edo_core_msgs/LoadConfigurationFileResponse.h>


namespace edo_core_msgs
{

struct LoadConfigurationFile
{

typedef LoadConfigurationFileRequest Request;
typedef LoadConfigurationFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadConfigurationFile
} // namespace edo_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::edo_core_msgs::LoadConfigurationFile > {
  static const char* value()
  {
    return "25458147911545c320c4c0a299eff763";
  }

  static const char* value(const ::edo_core_msgs::LoadConfigurationFile&) { return value(); }
};

template<>
struct DataType< ::edo_core_msgs::LoadConfigurationFile > {
  static const char* value()
  {
    return "edo_core_msgs/LoadConfigurationFile";
  }

  static const char* value(const ::edo_core_msgs::LoadConfigurationFile&) { return value(); }
};


// service_traits::MD5Sum< ::edo_core_msgs::LoadConfigurationFileRequest> should match
// service_traits::MD5Sum< ::edo_core_msgs::LoadConfigurationFile >
template<>
struct MD5Sum< ::edo_core_msgs::LoadConfigurationFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::LoadConfigurationFile >::value();
  }
  static const char* value(const ::edo_core_msgs::LoadConfigurationFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::LoadConfigurationFileRequest> should match
// service_traits::DataType< ::edo_core_msgs::LoadConfigurationFile >
template<>
struct DataType< ::edo_core_msgs::LoadConfigurationFileRequest>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::LoadConfigurationFile >::value();
  }
  static const char* value(const ::edo_core_msgs::LoadConfigurationFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::edo_core_msgs::LoadConfigurationFileResponse> should match
// service_traits::MD5Sum< ::edo_core_msgs::LoadConfigurationFile >
template<>
struct MD5Sum< ::edo_core_msgs::LoadConfigurationFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::LoadConfigurationFile >::value();
  }
  static const char* value(const ::edo_core_msgs::LoadConfigurationFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::LoadConfigurationFileResponse> should match
// service_traits::DataType< ::edo_core_msgs::LoadConfigurationFile >
template<>
struct DataType< ::edo_core_msgs::LoadConfigurationFileResponse>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::LoadConfigurationFile >::value();
  }
  static const char* value(const ::edo_core_msgs::LoadConfigurationFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_LOADCONFIGURATIONFILE_H
