// Generated by gencpp from file edo_core_msgs/LoadConfigurationFileResponse.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_LOADCONFIGURATIONFILERESPONSE_H
#define EDO_CORE_MSGS_MESSAGE_LOADCONFIGURATIONFILERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct LoadConfigurationFileResponse_
{
  typedef LoadConfigurationFileResponse_<ContainerAllocator> Type;

  LoadConfigurationFileResponse_()
    : result(0)  {
    }
  LoadConfigurationFileResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LoadConfigurationFileResponse_

typedef ::edo_core_msgs::LoadConfigurationFileResponse_<std::allocator<void> > LoadConfigurationFileResponse;

typedef boost::shared_ptr< ::edo_core_msgs::LoadConfigurationFileResponse > LoadConfigurationFileResponsePtr;
typedef boost::shared_ptr< ::edo_core_msgs::LoadConfigurationFileResponse const> LoadConfigurationFileResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator1> & lhs, const ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator1> & lhs, const ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25458147911545c320c4c0a299eff763";
  }

  static const char* value(const ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25458147911545c3ULL;
  static const uint64_t static_value2 = 0x20c4c0a299eff763ULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/LoadConfigurationFileResponse";
  }

  static const char* value(const ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 result\n"
"\n"
;
  }

  static const char* value(const ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LoadConfigurationFileResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::LoadConfigurationFileResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_LOADCONFIGURATIONFILERESPONSE_H
