// Generated by gencpp from file edo_core_msgs/MovementFeedback.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_MOVEMENTFEEDBACK_H
#define EDO_CORE_MSGS_MESSAGE_MOVEMENTFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct MovementFeedback_
{
  typedef MovementFeedback_<ContainerAllocator> Type;

  MovementFeedback_()
    : type(0)
    , data(0)  {
    }
  MovementFeedback_(const ContainerAllocator& _alloc)
    : type(0)
    , data(0)  {
  (void)_alloc;
    }



   typedef int8_t _type_type;
  _type_type type;

   typedef int8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MovementFeedback_

typedef ::edo_core_msgs::MovementFeedback_<std::allocator<void> > MovementFeedback;

typedef boost::shared_ptr< ::edo_core_msgs::MovementFeedback > MovementFeedbackPtr;
typedef boost::shared_ptr< ::edo_core_msgs::MovementFeedback const> MovementFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::MovementFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::MovementFeedback_<ContainerAllocator1> & lhs, const ::edo_core_msgs::MovementFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::MovementFeedback_<ContainerAllocator1> & lhs, const ::edo_core_msgs::MovementFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73ae55e61682758d03f77457371057c2";
  }

  static const char* value(const ::edo_core_msgs::MovementFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73ae55e61682758dULL;
  static const uint64_t static_value2 = 0x03f77457371057c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/MovementFeedback";
  }

  static const char* value(const ::edo_core_msgs::MovementFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 type\n"
"int8 data\n"
;
  }

  static const char* value(const ::edo_core_msgs::MovementFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovementFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::MovementFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::MovementFeedback_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "data: ";
    Printer<int8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_MOVEMENTFEEDBACK_H
