// Generated by gencpp from file edo_core_msgs/NodeSwVersion.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_NODESWVERSION_H
#define EDO_CORE_MSGS_MESSAGE_NODESWVERSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct NodeSwVersion_
{
  typedef NodeSwVersion_<ContainerAllocator> Type;

  NodeSwVersion_()
    : id(0)
    , version()  {
    }
  NodeSwVersion_(const ContainerAllocator& _alloc)
    : id(0)
    , version(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _version_type;
  _version_type version;





  typedef boost::shared_ptr< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> const> ConstPtr;

}; // struct NodeSwVersion_

typedef ::edo_core_msgs::NodeSwVersion_<std::allocator<void> > NodeSwVersion;

typedef boost::shared_ptr< ::edo_core_msgs::NodeSwVersion > NodeSwVersionPtr;
typedef boost::shared_ptr< ::edo_core_msgs::NodeSwVersion const> NodeSwVersionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::NodeSwVersion_<ContainerAllocator1> & lhs, const ::edo_core_msgs::NodeSwVersion_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.version == rhs.version;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::NodeSwVersion_<ContainerAllocator1> & lhs, const ::edo_core_msgs::NodeSwVersion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32142cb8c6603cabc4c4b47ff49034a7";
  }

  static const char* value(const ::edo_core_msgs::NodeSwVersion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32142cb8c6603cabULL;
  static const uint64_t static_value2 = 0xc4c4b47ff49034a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/NodeSwVersion";
  }

  static const char* value(const ::edo_core_msgs::NodeSwVersion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 id\n"
"string version\n"
;
  }

  static const char* value(const ::edo_core_msgs::NodeSwVersion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NodeSwVersion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::NodeSwVersion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::NodeSwVersion_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.id);
    s << indent << "version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_NODESWVERSION_H
