// Generated by gencpp from file edo_core_msgs/Point.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_POINT_H
#define EDO_CORE_MSGS_MESSAGE_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <edo_core_msgs/CartesianPose.h>

namespace edo_core_msgs
{
template <class ContainerAllocator>
struct Point_
{
  typedef Point_<ContainerAllocator> Type;

  Point_()
    : data_type(0)
    , cartesian_data()
    , joints_mask(0)
    , joints_data()  {
    }
  Point_(const ContainerAllocator& _alloc)
    : data_type(0)
    , cartesian_data(_alloc)
    , joints_mask(0)
    , joints_data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type_type;
  _data_type_type data_type;

   typedef  ::edo_core_msgs::CartesianPose_<ContainerAllocator>  _cartesian_data_type;
  _cartesian_data_type cartesian_data;

   typedef uint64_t _joints_mask_type;
  _joints_mask_type joints_mask;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _joints_data_type;
  _joints_data_type joints_data;





  typedef boost::shared_ptr< ::edo_core_msgs::Point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::Point_<ContainerAllocator> const> ConstPtr;

}; // struct Point_

typedef ::edo_core_msgs::Point_<std::allocator<void> > Point;

typedef boost::shared_ptr< ::edo_core_msgs::Point > PointPtr;
typedef boost::shared_ptr< ::edo_core_msgs::Point const> PointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::Point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::Point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::Point_<ContainerAllocator1> & lhs, const ::edo_core_msgs::Point_<ContainerAllocator2> & rhs)
{
  return lhs.data_type == rhs.data_type &&
    lhs.cartesian_data == rhs.cartesian_data &&
    lhs.joints_mask == rhs.joints_mask &&
    lhs.joints_data == rhs.joints_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::Point_<ContainerAllocator1> & lhs, const ::edo_core_msgs::Point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::Point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::Point_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::Point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::Point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26543d454cca7ceed4ebc194450e80d4";
  }

  static const char* value(const ::edo_core_msgs::Point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26543d454cca7ceeULL;
  static const uint64_t static_value2 = 0xd4ebc194450e80d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/Point";
  }

  static const char* value(const ::edo_core_msgs::Point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 data_type\n"
"edo_core_msgs/CartesianPose cartesian_data\n"
"uint64 joints_mask\n"
"float32[] joints_data\n"
"================================================================================\n"
"MSG: edo_core_msgs/CartesianPose\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 a\n"
"float32 e\n"
"float32 r\n"
"string config_flags\n"
;
  }

  static const char* value(const ::edo_core_msgs::Point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::Point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data_type);
      stream.next(m.cartesian_data);
      stream.next(m.joints_mask);
      stream.next(m.joints_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::Point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::Point_<ContainerAllocator>& v)
  {
    s << indent << "data_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data_type);
    s << indent << "cartesian_data: ";
    s << std::endl;
    Printer< ::edo_core_msgs::CartesianPose_<ContainerAllocator> >::stream(s, indent + "  ", v.cartesian_data);
    s << indent << "joints_mask: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.joints_mask);
    s << indent << "joints_data[]" << std::endl;
    for (size_t i = 0; i < v.joints_data.size(); ++i)
    {
      s << indent << "  joints_data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joints_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_POINT_H
