// Generated by gencpp from file edo_core_msgs/SystemCommandSrvResponse.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_SYSTEMCOMMANDSRVRESPONSE_H
#define EDO_CORE_MSGS_MESSAGE_SYSTEMCOMMANDSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct SystemCommandSrvResponse_
{
  typedef SystemCommandSrvResponse_<ContainerAllocator> Type;

  SystemCommandSrvResponse_()
    : res()  {
    }
  SystemCommandSrvResponse_(const ContainerAllocator& _alloc)
    : res(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SystemCommandSrvResponse_

typedef ::edo_core_msgs::SystemCommandSrvResponse_<std::allocator<void> > SystemCommandSrvResponse;

typedef boost::shared_ptr< ::edo_core_msgs::SystemCommandSrvResponse > SystemCommandSrvResponsePtr;
typedef boost::shared_ptr< ::edo_core_msgs::SystemCommandSrvResponse const> SystemCommandSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator1> & lhs, const ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.res == rhs.res;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator1> & lhs, const ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "53af918a2a4a2a182c184142fff49b0c";
  }

  static const char* value(const ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x53af918a2a4a2a18ULL;
  static const uint64_t static_value2 = 0x2c184142fff49b0cULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/SystemCommandSrvResponse";
  }

  static const char* value(const ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string res\n"
"\n"
;
  }

  static const char* value(const ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemCommandSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::SystemCommandSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_SYSTEMCOMMANDSRVRESPONSE_H
