// Generated by gencpp from file edo_core_msgs/SystemCommandSrvRequest.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_SYSTEMCOMMANDSRVREQUEST_H
#define EDO_CORE_MSGS_MESSAGE_SYSTEMCOMMANDSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edo_core_msgs
{
template <class ContainerAllocator>
struct SystemCommandSrvRequest_
{
  typedef SystemCommandSrvRequest_<ContainerAllocator> Type;

  SystemCommandSrvRequest_()
    : command(0)
    , data()  {
    }
  SystemCommandSrvRequest_(const ContainerAllocator& _alloc)
    : command(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SystemCommandSrvRequest_

typedef ::edo_core_msgs::SystemCommandSrvRequest_<std::allocator<void> > SystemCommandSrvRequest;

typedef boost::shared_ptr< ::edo_core_msgs::SystemCommandSrvRequest > SystemCommandSrvRequestPtr;
typedef boost::shared_ptr< ::edo_core_msgs::SystemCommandSrvRequest const> SystemCommandSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator1> & lhs, const ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator1> & lhs, const ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edo_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "427d96602650e56607ce37413cf89d2a";
  }

  static const char* value(const ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x427d96602650e566ULL;
  static const uint64_t static_value2 = 0x07ce37413cf89d2aULL;
};

template<class ContainerAllocator>
struct DataType< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edo_core_msgs/SystemCommandSrvRequest";
  }

  static const char* value(const ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 command\n"
"string data\n"
;
  }

  static const char* value(const ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemCommandSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edo_core_msgs::SystemCommandSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_SYSTEMCOMMANDSRVREQUEST_H
