// Generated by gencpp from file edo_core_msgs/SystemCommandSrv.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_SYSTEMCOMMANDSRV_H
#define EDO_CORE_MSGS_MESSAGE_SYSTEMCOMMANDSRV_H

#include <ros/service_traits.h>


#include <edo_core_msgs/SystemCommandSrvRequest.h>
#include <edo_core_msgs/SystemCommandSrvResponse.h>


namespace edo_core_msgs
{

struct SystemCommandSrv
{

typedef SystemCommandSrvRequest Request;
typedef SystemCommandSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SystemCommandSrv
} // namespace edo_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::edo_core_msgs::SystemCommandSrv > {
  static const char* value()
  {
    return "d5c8cf85d0eda7295fdc65a0bd92fc68";
  }

  static const char* value(const ::edo_core_msgs::SystemCommandSrv&) { return value(); }
};

template<>
struct DataType< ::edo_core_msgs::SystemCommandSrv > {
  static const char* value()
  {
    return "edo_core_msgs/SystemCommandSrv";
  }

  static const char* value(const ::edo_core_msgs::SystemCommandSrv&) { return value(); }
};


// service_traits::MD5Sum< ::edo_core_msgs::SystemCommandSrvRequest> should match
// service_traits::MD5Sum< ::edo_core_msgs::SystemCommandSrv >
template<>
struct MD5Sum< ::edo_core_msgs::SystemCommandSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::SystemCommandSrv >::value();
  }
  static const char* value(const ::edo_core_msgs::SystemCommandSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::SystemCommandSrvRequest> should match
// service_traits::DataType< ::edo_core_msgs::SystemCommandSrv >
template<>
struct DataType< ::edo_core_msgs::SystemCommandSrvRequest>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::SystemCommandSrv >::value();
  }
  static const char* value(const ::edo_core_msgs::SystemCommandSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::edo_core_msgs::SystemCommandSrvResponse> should match
// service_traits::MD5Sum< ::edo_core_msgs::SystemCommandSrv >
template<>
struct MD5Sum< ::edo_core_msgs::SystemCommandSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::SystemCommandSrv >::value();
  }
  static const char* value(const ::edo_core_msgs::SystemCommandSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::SystemCommandSrvResponse> should match
// service_traits::DataType< ::edo_core_msgs::SystemCommandSrv >
template<>
struct DataType< ::edo_core_msgs::SystemCommandSrvResponse>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::SystemCommandSrv >::value();
  }
  static const char* value(const ::edo_core_msgs::SystemCommandSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_SYSTEMCOMMANDSRV_H
