// Generated by gencpp from file edo_core_msgs/ToolConfiguration.msg
// DO NOT EDIT!


#ifndef EDO_CORE_MSGS_MESSAGE_TOOLCONFIGURATION_H
#define EDO_CORE_MSGS_MESSAGE_TOOLCONFIGURATION_H

#include <ros/service_traits.h>


#include <edo_core_msgs/ToolConfigurationRequest.h>
#include <edo_core_msgs/ToolConfigurationResponse.h>


namespace edo_core_msgs
{

struct ToolConfiguration
{

typedef ToolConfigurationRequest Request;
typedef ToolConfigurationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ToolConfiguration
} // namespace edo_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::edo_core_msgs::ToolConfiguration > {
  static const char* value()
  {
    return "125c31b70065f35442db81fd12ebc5e5";
  }

  static const char* value(const ::edo_core_msgs::ToolConfiguration&) { return value(); }
};

template<>
struct DataType< ::edo_core_msgs::ToolConfiguration > {
  static const char* value()
  {
    return "edo_core_msgs/ToolConfiguration";
  }

  static const char* value(const ::edo_core_msgs::ToolConfiguration&) { return value(); }
};


// service_traits::MD5Sum< ::edo_core_msgs::ToolConfigurationRequest> should match
// service_traits::MD5Sum< ::edo_core_msgs::ToolConfiguration >
template<>
struct MD5Sum< ::edo_core_msgs::ToolConfigurationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::ToolConfiguration >::value();
  }
  static const char* value(const ::edo_core_msgs::ToolConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::ToolConfigurationRequest> should match
// service_traits::DataType< ::edo_core_msgs::ToolConfiguration >
template<>
struct DataType< ::edo_core_msgs::ToolConfigurationRequest>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::ToolConfiguration >::value();
  }
  static const char* value(const ::edo_core_msgs::ToolConfigurationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::edo_core_msgs::ToolConfigurationResponse> should match
// service_traits::MD5Sum< ::edo_core_msgs::ToolConfiguration >
template<>
struct MD5Sum< ::edo_core_msgs::ToolConfigurationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::edo_core_msgs::ToolConfiguration >::value();
  }
  static const char* value(const ::edo_core_msgs::ToolConfigurationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::edo_core_msgs::ToolConfigurationResponse> should match
// service_traits::DataType< ::edo_core_msgs::ToolConfiguration >
template<>
struct DataType< ::edo_core_msgs::ToolConfigurationResponse>
{
  static const char* value()
  {
    return DataType< ::edo_core_msgs::ToolConfiguration >::value();
  }
  static const char* value(const ::edo_core_msgs::ToolConfigurationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EDO_CORE_MSGS_MESSAGE_TOOLCONFIGURATION_H
