(cl:in-package edo_core_msgs-msg)
(cl:export '(KP-VAL
          KP
          TI-VAL
          TI
          TD-VAL
          TD
          SAT-VAL
          SAT
          KFF-VAL
          KFF
          MAX-VAL
          MAX
          KPV-VAL
          KPV
          TIV-VAL
          TIV
          TDV-VAL
          TDV
          SATV-VAL
          SATV
          KFFV-VAL
          KFFV
          MAXV-VAL
          MAXV
          KPT-VAL
          KPT
          TIT-VAL
          TIT
          TDT-VAL
          TDT
          SATT-VAL
          SATT
          KFFT-VAL
          KFFT
          MAXT-VAL
          MAXT
          KT-VAL
          KT
))